# Generated by Django 3.1.5 on 2021-08-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order Total Dlls')),
                ('email_address', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('billingName', models.CharField(blank=True, max_length=255)),
                ('billingAddress1', models.CharField(blank=True, max_length=255)),
                ('billingCity', models.CharField(blank=True, max_length=255)),
                ('billingPostCode', models.CharField(blank=True, max_length=255)),
                ('billingCountry', models.CharField(blank=True, max_length=255)),
                ('ShippingName', models.CharField(blank=True, max_length=255)),
                ('ShippingAddress1', models.CharField(blank=True, max_length=255)),
                ('ShippingCity', models.CharField(blank=True, max_length=255)),
                ('ShippingPostCode', models.CharField(blank=True, max_length=255)),
                ('ShippingCountry', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dlls')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.order')),
            ],
            options={
                'db_table': 'orderItem',
            },
        ),
    ]
